/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestiones.Gestionar;
import Gestiones.ConexionBaseDatos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author kevin
 */
public class CambiarRol extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CambiarRol.class.getName());

    /**
     * Creates new form Registrarse
     */
    public CambiarRol() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(750, 520);
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearRegistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtRegistrarUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();
        VolverB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Crear Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 280, 40));

        btnCrearRegistrar.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        btnCrearRegistrar.setText("Actualizar");
        btnCrearRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 140, 50));

        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, 30));
        jPanel1.add(txtRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 230, 40));

        jLabel5.setText("Nuevo Rol");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 30));
        jPanel1.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 230, 40));

        VolverB.setText("Volver");
        VolverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBActionPerformed(evt);
            }
        });
        jPanel1.add(VolverB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    HU-04: Como administrador, quiero que al registrar un usuario nuevo se verifique que el correo
    electrónico no esté ya registrado, para evitar duplicados en la base de datos.
    */
    private void btnCrearRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRegistrarActionPerformed
        String idText = txtRegistrarUsuario.getText().trim();
        String rol = txtRol.getText().trim();

        // Validar que no esté vacío y que sea numérico
        if (idText.isEmpty() || rol.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        int idUsuario;
        try {
            idUsuario = Integer.parseInt(idText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
            return;
        }

        if (!Gestionar.existeUsuario(idUsuario)) {
            JOptionPane.showMessageDialog(this, "El usuario con ID " + idUsuario + " no existe.");
            return;
        }

        // Ahora sí insertamos el rol
    // Ahora actualizamos el rol en vez de insertar
        try (Connection conn = ConexionBaseDatos.conectar()) {
            String sqlRol = "UPDATE rol SET numero_rol = ? WHERE id_usuario = ?";
            PreparedStatement psRol = conn.prepareStatement(sqlRol);
            psRol.setInt(1, Integer.parseInt(rol));   // nuevo rol
            psRol.setInt(2, idUsuario);               // usuario al que aplicamos el cambio
            int filas = psRol.executeUpdate();

            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Rol actualizado con éxito al usuario " + idUsuario);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el rol para este usuario.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "❌ Error asignando rol: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCrearRegistrarActionPerformed

    private void VolverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBActionPerformed
        // TODO add your handling code here:
        Principal principalVentana = new Principal(); // 
        principalVentana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CambiarRol().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VolverB;
    private javax.swing.JButton btnCrearRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRegistrarUsuario;
    private javax.swing.JTextField txtRol;
    // End of variables declaration//GEN-END:variables
}