/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import javax.swing.JOptionPane;

/**
 *
 * @author adrianlopez
 */
//HU-03
public class CodigoVerificacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CodigoVerificacion.class.getName());

    /**
     * Creates new form CodigoVerificacion
     */
    //codigo donde se recibe el del panel anterior
    private int codigoEnviado; // Aquí se guarda el código

    // Método para recibir el código desde InicioSesion
    public void setCodigo(int codigo) {
        this.codigoEnviado = codigo;
    }
    
    public CodigoVerificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoJText = new javax.swing.JTextField();
        EnviarCodigoJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(630, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresar el codigo de verificacion");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 390, 100));

        codigoJText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(codigoJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 340, -1));

        EnviarCodigoJButton.setText("Enviar");
        EnviarCodigoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarCodigoJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EnviarCodigoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 330, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarCodigoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarCodigoJButtonActionPerformed
        // TODO add your handling code here:
        //toma lo que haya en el JTextField 
        String CodigoV = codigoJText.getText().trim();
        
        //mira si no esta vacio
        if (CodigoV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el codigo por favor");
            return;
        }
        
        //try y catch
        try{
            //convierte lo que haya en el CodigoV a int
            int CodigoIngresado = Integer.parseInt(CodigoV);
            //compara CodigoV con codigoEnviado
            if(CodigoIngresado == codigoEnviado){
                //Abre la nueva ventana y cierra la actual.
                new Principal().setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this, "Código Incorrecto: " + codigoEnviado);
            }
        //envia una advertencia de que el codigo no es valido.
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un código numérico válido, este codigo solo acepta numeros");
        }
    }//GEN-LAST:event_EnviarCodigoJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CodigoVerificacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarCodigoJButton;
    private javax.swing.JTextField codigoJText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
