/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestiones.Gestionar;
import Gestiones.ConexionBaseDatos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author kevin
 */
public class CrearUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearUsuario.class.getName());

    /**
     * Creates new form Registrarse
     */
    public CrearUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(750, 520);
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRegistrarCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRegistrarContrasena = new javax.swing.JTextField();
        btnCrearRegistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtRegistrarUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Crear Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 280, 40));

        jLabel2.setText("Correo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, 30));
        jPanel1.add(txtRegistrarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 230, 40));

        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 30));
        jPanel1.add(txtRegistrarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 230, 40));

        btnCrearRegistrar.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        btnCrearRegistrar.setText("Crear");
        btnCrearRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 140, 50));

        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, 30));
        jPanel1.add(txtRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 230, 40));

        jLabel5.setText("Rol");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 150, -1));
        jPanel1.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    HU-04: Como administrador, quiero que al registrar un usuario nuevo se verifique que el correo
    electrónico no esté ya registrado, para evitar duplicados en la base de datos.
    */
    private void btnCrearRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRegistrarActionPerformed
        //agrego .trim() para que los campos necesiten estar llenos antes de enviar.
        String correo = txtRegistrarCorreo.getText().trim();
        String usuario = txtRegistrarUsuario.getText().trim();
        String password = txtRegistrarContrasena.getText().trim();
        String rol = txtRol.getText().trim();
    
        // Validación de campos vacios
        if (correo.isEmpty() || usuario.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios por favor ingresarlos datos");
            return;
        }

        if (Gestionar.existeUsuarioOCorreo(usuario, correo)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El usuario o correo ya está registrado, por lo que no "
                    + "deberia intentar volver a ingresar sus datos");
            return;
        }

        if (Gestionar.registrarUsuario(usuario, correo, password)) {
            try (Connection conn = ConexionBaseDatos.conectar()) {
                // 1. Recuperar el id del usuario recién insertado
                String sqlId = "SELECT id_usuario FROM usuarios WHERE correo = ?";
                PreparedStatement psId = conn.prepareStatement(sqlId);
                psId.setString(1, correo);
                ResultSet rs = psId.executeQuery();

                if (rs.next()) {
                    int idUsuario = rs.getInt("id_usuario");

                    // 2. Insertar el rol
                    String sqlRol = "INSERT INTO rol(id_usuario, numero_rol) VALUES (?, ?)";
                    PreparedStatement psRol = conn.prepareStatement(sqlRol);
                    psRol.setInt(1, idUsuario);
                    psRol.setInt(2, Integer.parseInt(rol));
                    psRol.executeUpdate();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error asignando rol: " + e.getMessage());
            }

            JOptionPane.showMessageDialog(this, "Usuario creado con éxito con su rol asignado");
            Principal is = new Principal();
            is.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar posible duplicado o tipo de datos incorrecto.");
        }

 
    }//GEN-LAST:event_btnCrearRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRegistrarContrasena;
    private javax.swing.JTextField txtRegistrarCorreo;
    private javax.swing.JTextField txtRegistrarUsuario;
    private javax.swing.JTextField txtRol;
    // End of variables declaration//GEN-END:variables
}
