/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestiones.ConexionBaseDatos;
import static inventario.Inventario.enviarCorreo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Random;
        

/**
 *
 * @author kevin
 */
public class InicioSesion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioSesion.class.getName());

    /**
     * Creates new form InicioSision
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        btnRegistrarse = new javax.swing.JButton();
        btnIngresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Inicio de sesion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 280, 40));

        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 30));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 230, 40));

        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 30));
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 230, 40));

        btnRegistrarse.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        btnRegistrarse.setText("Registrar");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 140, 50));

        btnIngresar1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        btnIngresar1.setText("Ingresar");
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        Registrarse registrarse = new Registrarse();
        registrarse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    //AUTOR ADRIAN
    //Esta parte del codigo lo que hace es validar la clave y contraseña para poder iniciar sesion por el momento
    //solo verifica la clave que se ingreso no si esta cumple con el 
    //estandar de seguridad (8 caracteres, numeros, mayusculas y minusculas
    //y caracteres especiales)
    //HU-01
    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        /*estos dos .getText obtienen los datos de los JTextField 
        y el .trim lo que hace es quitar los espacion al inio y final*/
        //agrego .trim() para que los campos necesiten estar llenos antes de enviar.
        String usuario = txtUsuario.getText().trim();
        String contrasena = txtContrasena.getText().trim();

        /*
        esta parte verifica que lo que se este ingresando no sea "" */
        if (usuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese usuario y contraseña");
            return;
        }
        
        if (!VerificarClaveSeguridad(contrasena)) {
             JOptionPane.showMessageDialog(this, "Se sugiere cambiar la clave por una mas segura.\n Debe tener al menos 8 caracteres, incluir mayusculas, minusculas, numeros y un caracter especial.");
         }
        
        //consulta sql para ver si el usuario existe
        String sql = "SELECT correo FROM usuarios WHERE usuario = ? AND `contraseña` = ?";


        try (Connection conn = ConexionBaseDatos.conectar();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, usuario);
            ps.setString(2, contrasena);
            
            //HU-03
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String correoUsuario = rs.getString("correo");

                    //esto abre la siguiente ventana
                    /*por el momento necesito crear el un codigo aleatorio
                    y que sea enviado al correo para que sea usado como verificacion de dos factores*/
                    Random random = new Random();
                    int CodigoSeguridad = 1000 + random.nextInt(9000);
                    //convierte el numero de seguridad a STR para que la funcion me lo acepte sin problema
                    String codigoStr = String.valueOf(CodigoSeguridad);
                    //por el momento estoy usando mi correo para probar el funcionamiento
                    //recordar poner el @gmail
                    enviarCorreo(correoUsuario, "Clave de acceso", codigoStr);
                    CodigoVerificacion ventanaCodigo = new CodigoVerificacion();
                    ventanaCodigo.setCodigo(CodigoSeguridad); // asigna el código a la ventana que vas a mostrar
                    ventanaCodigo.setVisible(true);
                    
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos, pruebe revisando si son correctos");
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectarse a la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnIngresar1ActionPerformed

  
    
    //lo que hace es solo verificar si la clave del usuario cumple con lo requerido en el punto HU-01
    //no hace nada mas que dar 
    private boolean VerificarClaveSeguridad(String clave) {
        //esto de aqui es lo que toma como ejemplo para saber como tiene que ser la clave.
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&.,;:_-]).{8,}$";
        return clave.matches(regex);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicioSesion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
