/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestiones.Gestionar;

/**
 *
 * @author kevin
 */
public class Registrarse extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrarse.class.getName());

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(750, 520);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRegistrarCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRegistrarContrasena = new javax.swing.JTextField();
        btnCrearRegistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtRegistrarUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Registrarse");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 210, 40));

        jLabel2.setText("Correo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, 30));
        jPanel1.add(txtRegistrarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 230, 40));

        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 30));
        jPanel1.add(txtRegistrarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 230, 40));

        btnCrearRegistrar.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        btnCrearRegistrar.setText("Registrar");
        btnCrearRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 140, 50));

        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, 30));
        jPanel1.add(txtRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    HU-04: Como administrador, quiero que al registrar un usuario nuevo se verifique que el correo
    electrónico no esté ya registrado, para evitar duplicados en la base de datos.
    */
    private void btnCrearRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRegistrarActionPerformed
    String correo = txtRegistrarCorreo.getText().trim();
    String usuario = txtRegistrarUsuario.getText().trim();
    String password = txtRegistrarContrasena.getText().trim();
    
    // Validación de campos vacíos
    if (correo.isEmpty() || usuario.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
        return;
    }
    
    if (Gestionar.existeUsuarioOCorreo(usuario, correo)) {
        javax.swing.JOptionPane.showMessageDialog(this, "El usuario o correo ya está registrado");
        return;
    }
    
    if (Gestionar.registrarUsuario(usuario, correo, password)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado con éxito");
        this.dispose(); // o setVisible(false)
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar (posible duplicado o error).");
    }
     
 
    }//GEN-LAST:event_btnCrearRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrarse().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRegistrarContrasena;
    private javax.swing.JTextField txtRegistrarCorreo;
    private javax.swing.JTextField txtRegistrarUsuario;
    // End of variables declaration//GEN-END:variables
}
